{
 "title": "Github",
 "description": "This dashboard contains a sample of some of the various features and display methods available in the GitHub datasource.",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Commits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Github_Project_Commits{}" }
   ]
  },
  {
   "title": "Issues Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Github_Project_Issues_Open{}" }
   ]
  },
  {
   "title": "Active Issues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Github_Project_Issues_Open_Date{}"
    }
   ]
  },
  {
   "title": "Active Pull Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Github_Project_Pull_Request" }
   ]
  },
  {
   "title": "Pull Requests Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Github_Project_Pull_Request{}" }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Github_Project_All_Repos{}" }
   ]
  },
  {
   "title": "Pull Requests",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "Github_Project_Pull_Request{}" }
   ]
  },
  {
   "title": "Commits Description",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "Github_Project_Commits{}" }
   ]
  },
  {
   "title": "Issues",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expr": "Github_Project_Issues_Open{}" }
   ]
  },
  {
   "title": "Contributors",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "Github_Project_Cont{}" }
   ]
  }
 ]
}