{
 "title": "Redmine Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Opened",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Redmine_Openissues{}" }
   ]
  },
  {
   "title": "Closed",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Redmine_Closedissues{}" }
   ]
  },
  {
   "title": "Resolved",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Redmine_Resolvedissues{}" }
   ]
  },
  {
   "title": "Feedback",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Redmine_Feedbackissues{}" }
   ]
  },
  {
   "title": "In progress",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Redmine_Inprogressissues{}" }
   ]
  },
  {
   "title": "On hold",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Redmine_Onholdissues{}" }
   ]
  },
  {
   "title": "Due by Today",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "Redmine_Duedate{}" }
   ]
  }
 ]
}